### ISSUE TITLE
metadatafile

### ISSUE THREAD

**Issue by CarolineOhrman** [FOI-Bioinformatics/repgenr#15]
It does'nt exist any bac120_metadata_r220.tar.gz in the 220 release as in 207 and 214.

`repgenr metadata -r 220.0 --version bac120 -d all -l genus -tg Francisella -wd francisella --outgroup_accession GCF_003290445.1`
Output
```
[INFO][TIMESTAMP][START] Wed 07 Aug 2024 11:08:53 AM CEST
Downloading metadata-file from GTDB...
Could not fetch metadata from:
https://data.gtdb.ecogenomic.org/releases/release220/220.0/bac120_metadata_r220.tar.gz
Make sure that the release version, database version, and dataset version exists.
```

I downloaded the file https://data.gtdb.ecogenomic.org/releases/release220/220.0/bac120_metadata_r220.tsv.gz manually and used the --metadata_path argument that worked.

**Comment by jaclew** [comment]
The cause for this error is due to GTDB changing the format of their metadata file, in previous versions it was "bac120_metadata_r*.**tsv**.gz" but in newer versions it is "bac120_metadata_r*.**tar**.gz". Repgenr has been updated to handle both formats in the latest version of the code, please update your installation.
